name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  test_matrix:
    strategy:
      matrix:
        include:
          - os: windows-latest
            artifact_name: ${{ github.event.repository.name }}.exe
            suffix: ".exe"
          - os: ubuntu-22.04
            artifact_name: ${{ github.event.repository.name }}
            suffix: ""
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Disable man-db auto update (until fixed in Ubuntu) # will be fixed by 2025-11-14 https://github.com/actions/runner-images/issues/13213
        if: runner.os == 'Linux'
        run: |
          export DEBIAN_FRONTEND=noninteractive
          echo "set man-db/auto-update false" | sudo debconf-communicate
          sudo dpkg-reconfigure -f noninteractive man-db
      - name: Install libpcap-dev (apt-get)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libpcap-dev
      - run: rustup component add clippy
      - run: cargo check --release
      - run: cargo fmt --check
      - run: cargo test --release --features static-libpcap
      - run: cargo clippy --release
      - run: cargo build --release --features static-libpcap
      - if: ${{matrix.artifact_name}}
        name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact_name }}
          path: target/release/irminsul${{ matrix.suffix }}
